In [69]:
# chargement des librairies
import glob as g
import pandas as pd
import numpy as np
from datetime import datetime
import os

In [2]:
# dictionnaire pour changer les codes des localités en noms des localités
location_mapper = {"IDCJDW2002": "Albury",
                   "IDCJDW2005": "BadgerysCreek",
                   "IDCJDW2029": "Cobar",
                   "IDCJDW2097": "Newcastle", 
                   "IDCJDW2030": "CoffsHarbour",
                   "IDCJDW2084": "Moree",
                   "IDCJDW2099": "NorahHead",
                   "IDCJDW2100": "NorfolkIsland",
                   "IDCJDW2111": "Penrith",
                   "IDCJDW2119": "Richmond",
                   "IDCJDW2124": "Sydney",
                   "IDCJDW2125": "SydneyAirport",
                   "IDCJDW2139": "WaggaWagga",
                   "IDCJDW2145": "Williamtown", 
                   "IDCJDW2146": "Wollongong",
                   "IDCJDW2801": "Canberra",
                   "IDCJDW2802": "Tuggeranong",
                   "IDCJDW2804": "MountGinini",
                   "IDCJDW3005": "Ballarat",
                   "IDCJDW3008": "Bendigo",
                   "IDCJDW2142": "Sale",
                   "IDCJDW3049": "MelbourneAirport",
                   "IDCJDW3050": "Melbourne",
                   "IDCJDW3051": "Mildura", 
                   "IDCJDW3059": "Nhil",
                   "IDCJDW3068": "Portland",
                   "IDCJDW3079": "Watsonia",
                   "IDCJDW3101": "Dartmoor",
                   "IDCJDW4019": "Brisbane",
                   "IDCJDW4024": "Cairns",
                   "IDCJDW4050": "GoldCoast",
                   "IDCJDW4128": "Townsville",
                   "IDCJDW5081": "Adelaide",
                   "IDCJDW5041": "MountGambier", 
                   "IDCJDW5049": "Nuriootpa",
                   "IDCJDW5072": "Woomera",
                   "IDCJDW6001": "Albany",
                   "IDCJDW2143": "Witchcliffe",
                   "IDCJDW6108": "PearceRAAF",
                   "IDCJDW6110": "PerthAirport",
                   "IDCJDW6111": "Perth",
                   "IDCJDW6119": "SalmonGums",
                   "IDCJDW6138": "Walpole",
                   "IDCJDW7021": "Hobart", 
                   "IDCJDW7025": "Launceston",
                   "IDCJDW8002": "AliceSprings",
                   "IDCJDW8014": "Darwin",
                   "IDCJDW8024": "Katherine",
                   "IDCJDW8056": "Uluru"
                  }

location_mapper

{'IDCJDW2002': 'Albury',
 'IDCJDW2005': 'BadgerysCreek',
 'IDCJDW2029': 'Cobar',
 'IDCJDW2097': 'Newcastle',
 'IDCJDW2030': 'CoffsHarbour',
 'IDCJDW2084': 'Moree',
 'IDCJDW2099': 'NorahHead',
 'IDCJDW2100': 'NorfolkIsland',
 'IDCJDW2111': 'Penrith',
 'IDCJDW2119': 'Richmond',
 'IDCJDW2124': 'Sydney',
 'IDCJDW2125': 'SydneyAirport',
 'IDCJDW2139': 'WaggaWagga',
 'IDCJDW2145': 'Williamtown',
 'IDCJDW2146': 'Wollongong',
 'IDCJDW2801': 'Canberra',
 'IDCJDW2802': 'Tuggeranong',
 'IDCJDW2804': 'MountGinini',
 'IDCJDW3005': 'Ballarat',
 'IDCJDW3008': 'Bendigo',
 'IDCJDW2142': 'Sale',
 'IDCJDW3049': 'MelbourneAirport',
 'IDCJDW3050': 'Melbourne',
 'IDCJDW3051': 'Mildura',
 'IDCJDW3059': 'Nhil',
 'IDCJDW3068': 'Portland',
 'IDCJDW3079': 'Watsonia',
 'IDCJDW3101': 'Dartmoor',
 'IDCJDW4019': 'Brisbane',
 'IDCJDW4024': 'Cairns',
 'IDCJDW4050': 'GoldCoast',
 'IDCJDW4128': 'Townsville',
 'IDCJDW5081': 'Adelaide',
 'IDCJDW5041': 'MountGambier',
 'IDCJDW5049': 'Nuriootpa',
 'IDCJDW5072': 'Woomera',
 'IDCJDW6001': 'Albany',
 'IDCJDW2143': 'Witchcliffe',
 'IDCJDW6108': 'PearceRAAF',
 'IDCJDW6110': 'PerthAirport',
 'IDCJDW6111': 'Perth',
 'IDCJDW6119': 'SalmonGums',
 'IDCJDW6138': 'Walpole',
 'IDCJDW7021': 'Hobart',
 'IDCJDW7025': 'Launceston',
 'IDCJDW8002': 'AliceSprings',
 'IDCJDW8014': 'Darwin',
 'IDCJDW8024': 'Katherine',
 'IDCJDW8056': 'Uluru'}

In [3]:
# dictionnaire pour renommer l'ensemble des colonnes
columns_mapper = {"Minimum temperature (°C)": "mintemp",
                  "Maximum temperature (°C)": "maxtemp",
                  "Rainfall (mm)": "rainfall",
                  "Evaporation (mm)": "evaporation",
                  "Sunshine (hours)": "sunshine",
                  "Direction of maximum wind gust ": "windgustdir",
                  "Speed of maximum wind gust (km/h)": "windgustspeed",
                  "9am Temperature (°C)": "temp9am",
                  "9am relative humidity (%)": "humidity9am",
                  "9am cloud amount (oktas)": "cloud9am",
                  "9am wind direction": "winddir9am",
                  "9am wind speed (km/h)": "windspeed9am",
                  "9am MSL pressure (hPa)": "pressure9am",
                  "3pm Temperature (°C)": "temp3pm",
                  "3pm relative humidity (%)": "humidity3pm",
                  "3pm cloud amount (oktas)": "cloud3pm",
                  "3pm wind direction": "winddir3pm",
                  "3pm wind speed (km/h)": "windspeed3pm",
                  "3pm MSL pressure (hPa)": "pressure3pm",
                  "Year": "year",
                  "Month": "month",
                  "Day": "day",
                  "Location": "location",
                  "RainToday": "raintoday",
                  "RainTomorrow": "raintomorrow"                  
                 }


columns_mapper

{'Minimum temperature (°C)': 'mintemp',
 'Maximum temperature (°C)': 'maxtemp',
 'Rainfall (mm)': 'rainfall',
 'Evaporation (mm)': 'evaporation',
 'Sunshine (hours)': 'sunshine',
 'Direction of maximum wind gust ': 'windgustdir',
 'Speed of maximum wind gust (km/h)': 'windgustspeed',
 '9am Temperature (°C)': 'temp9am',
 '9am relative humidity (%)': 'humidity9am',
 '9am cloud amount (oktas)': 'cloud9am',
 '9am wind direction': 'winddir9am',
 '9am wind speed (km/h)': 'windspeed9am',
 '9am MSL pressure (hPa)': 'pressure9am',
 '3pm Temperature (°C)': 'temp3pm',
 '3pm relative humidity (%)': 'humidity3pm',
 '3pm cloud amount (oktas)': 'cloud3pm',
 '3pm wind direction': 'winddir3pm',
 '3pm wind speed (km/h)': 'windspeed3pm',
 '3pm MSL pressure (hPa)': 'pressure3pm',
 'Year': 'year',
 'Month': 'month',
 'Day': 'day',
 'Location': 'location',
 'RainToday': 'raintoday',
 'RainTomorrow': 'raintomorrow'}

In [4]:
# noms des colonnes (dans le bon ordre) à associer au fichier final
columns_order = ["location","mintemp","maxtemp","rainfall","evaporation","sunshine","windgustdir","windgustspeed",
                 "winddir9am","winddir3pm","windspeed9am","windspeed3pm","humidity9am","humidity3pm","pressure9am",
                 "pressure3pm","cloud9am","cloud3pm","temp9am","temp3pm","raintoday","raintomorrow","year","month","day"]

columns_order

['location',
 'mintemp',
 'maxtemp',
 'rainfall',
 'evaporation',
 'sunshine',
 'windgustdir',
 'windgustspeed',
 'winddir9am',
 'winddir3pm',
 'windspeed9am',
 'windspeed3pm',
 'humidity9am',
 'humidity3pm',
 'pressure9am',
 'pressure3pm',
 'cloud9am',
 'cloud3pm',
 'temp9am',
 'temp3pm',
 'raintoday',
 'raintomorrow',
 'year',
 'month',
 'day']

In [57]:
# noms des colonnes dans les fichiers cvs à manipuler
csv_col_names=['Location', 'Date', 'Minimum temperature (°C)', 'Maximum temperature (°C)',
               'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)',
               'Direction of maximum wind gust ', 'Speed of maximum wind gust (km/h)',
               'Time of maximum wind gust', '9am Temperature (°C)',
               '9am relative humidity (%)', '9am cloud amount (oktas)',
               '9am wind direction', '9am wind speed (km/h)', '9am MSL pressure (hPa)',
               '3pm Temperature (°C)', '3pm relative humidity (%)',
               '3pm cloud amount (oktas)', '3pm wind direction',
               '3pm wind speed (km/h)', '3pm MSL pressure (hPa)']

csv_col_names

['Location',
 'Date',
 'Minimum temperature (°C)',
 'Maximum temperature (°C)',
 'Rainfall (mm)',
 'Evaporation (mm)',
 'Sunshine (hours)',
 'Direction of maximum wind gust ',
 'Speed of maximum wind gust (km/h)',
 'Time of maximum wind gust',
 '9am Temperature (°C)',
 '9am relative humidity (%)',
 '9am cloud amount (oktas)',
 '9am wind direction',
 '9am wind speed (km/h)',
 '9am MSL pressure (hPa)',
 '3pm Temperature (°C)',
 '3pm relative humidity (%)',
 '3pm cloud amount (oktas)',
 '3pm wind direction',
 '3pm wind speed (km/h)',
 '3pm MSL pressure (hPa)']

In [58]:
# colonnes des variables numériques
num_cols = ['Minimum temperature (°C)', 'Maximum temperature (°C)', 'Rainfall (mm)', 'Evaporation (mm)', 'Sunshine (hours)',
            'Speed of maximum wind gust (km/h)', '9am Temperature (°C)', '9am relative humidity (%)', '9am cloud amount (oktas)',
            '9am MSL pressure (hPa)', '9am wind speed (km/h)', '3pm Temperature (°C)', '3pm relative humidity (%)', '3pm cloud amount (oktas)',
            '3pm wind speed (km/h)', '3pm MSL pressure (hPa)']

num_cols

['Minimum temperature (°C)',
 'Maximum temperature (°C)',
 'Rainfall (mm)',
 'Evaporation (mm)',
 'Sunshine (hours)',
 'Speed of maximum wind gust (km/h)',
 '9am Temperature (°C)',
 '9am relative humidity (%)',
 '9am cloud amount (oktas)',
 '9am MSL pressure (hPa)',
 '9am wind speed (km/h)',
 '3pm Temperature (°C)',
 '3pm relative humidity (%)',
 '3pm cloud amount (oktas)',
 '3pm wind speed (km/h)',
 '3pm MSL pressure (hPa)']

In [199]:
# extraction

def extract(folder):
    extracted_data = pd.DataFrame(columns = csv_col_names)
    
    for file in g.glob(folder):
        df = pd.read_csv(file, encoding = "ISO-8859-1", names = csv_col_names)

        text = df["Location"][1]
        code = text.split(".")[0].split(" ")[-1]
        df["Location"] = code

        df.dropna(thresh=3, axis=0, inplace=True)
        df.drop(index=df.index[0], axis=0, inplace=True)
        
        df['9am wind speed (km/h)'].replace({"Calm": 1}, inplace = True)
        df['3pm wind speed (km/h)'].replace({"Calm": 1}, inplace = True)
        
        df[num_cols] = df[num_cols].astype(float, errors='raise')

        extracted_data = pd.concat([extracted_data, df], ignore_index = True)
        extracted_data["Location"].replace(location_mapper, inplace = True)
          
    return extracted_data

In [200]:
# test de la fonction "extract"
#input_path = "../../datasets/raw/latest/" + "IDCJDW2002.202306.csv"
#input_path = "../../datasets/raw/latest/" + "IDCJDW2111.202306.csv"
#input_path = "../../datasets/raw/latest/" + "IDCJDW5081.202306.csv"
input_path = "../../datasets/raw/latest/*.csv"
extracted_data = extract(folder = input_path)
extracted_data

,Location,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,Ballarat,2023-07-1,5.1,11.5,2.2,NaN,NaN,S,33.0,23:52,...,8.0,SW,13.0,1024.4,8.1,92.0,8.0,S,24.0,1026.5
1,Ballarat,2023-07-2,6.2,9.6,0.6,NaN,NaN,SSE,35.0,07:45,...,8.0,SSE,20.0,1034.2,9.2,81.0,8.0,S,7.0,1033.3
2,Ballarat,2023-07-3,2.7,11.4,0.2,NaN,NaN,NNE,33.0,18:49,...,1.0,N,11.0,1030.0,10.4,70.0,4.0,N,17.0,1024.9
3,Ballarat,2023-07-4,4.8,10.4,0.8,NaN,NaN,N,43.0,13:14,...,8.0,NNE,15.0,1017.4,9.3,92.0,8.0,NNE,20.0,1012.2
4,Ballarat,2023-07-5,5.4,11.6,4.4,NaN,NaN,N,39.0,23:48,...,8.0,N,15.0,1012.7,10.7,73.0,1.0,NNW,28.0,1011.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396,Launceston,2023-07-15,9.6,12.6,3.0,NaN,NaN,NNW,37.0,00:07,...,8.0,NNW,17.0,NaN,11.9,43.0,NaN,WNW,17.0,NaN
2397,Launceston,2023-07-16,6.7,14.5,0.0,NaN,NaN,NNW,41.0,12:57,...,NaN,NNW,13.0,NaN,13.5,69.0,NaN,NNW,22.0,NaN
2398,Launceston,2023-07-17,8.4,15.0,0.0,NaN,NaN,NNW,41.0,13:02,...,8.0,NNW,13.0,NaN,14.5,64.0,6.0,NNW,19.0,NaN
2399,Launceston,2023-07-18,9.7,12.1,1.2,NaN,NaN,NNW,50.0,10:47,...,3.0,NNW,17.0,NaN,10.5,80.0,8.0,NNW,11.0,NaN
2400,Launceston,2023-07-19,0.7,NaN,1.4,NaN,NaN,NaN,NaN,NaN,...,NaN,S,6.0,NaN,11.2,49.0,NaN,NE,6.0,NaN

In [201]:
extracted_data.dtypes

Location                              object
Date                                  object
Minimum temperature (°C)             float64
Maximum temperature (°C)             float64
Rainfall (mm)                        float64
Evaporation (mm)                     float64
Sunshine (hours)                     float64
Direction of maximum wind gust        object
Speed of maximum wind gust (km/h)    float64
Time of maximum wind gust             object
9am Temperature (°C)                 float64
9am relative humidity (%)            float64
9am cloud amount (oktas)             float64
9am wind direction                    object
9am wind speed (km/h)                float64
9am MSL pressure (hPa)               float64
3pm Temperature (°C)                 float64
3pm relative humidity (%)            float64
3pm cloud amount (oktas)             float64
3pm wind direction                    object
3pm wind speed (km/h)                float64
3pm MSL pressure (hPa)               float64
dtype: object

In [202]:
# Transformation

def transform(data):
    data['Date'] = pd.to_datetime(data['Date'])
    data['Year'] = data['Date'].dt.year
    data['Month'] = data['Date'].dt.month
    data['Day'] = data['Date'].dt.day
    
    data.drop("Time of maximum wind gust", axis = 1, inplace=True)

    data["RainToday"] = data["Rainfall (mm)"] >= 1
    data["RainToday"].replace({False:"No", True: "Yes"}, inplace = True)

    res = pd.DataFrame(columns = data.columns)
    
    localities = data["Location"].unique()

    for city in localities:
        df = data[data["Location"] == city].copy()
        df.set_index('Date', inplace=True)
        df.sort_index(axis=0, level=None, ascending=True, inplace=True)
        df["RainTomorrow"] = df.shift(-1)["RainToday"]
        res = pd.concat([res, df], axis=0, ignore_index = True)

    res.rename(columns=columns_mapper, inplace=True)
    res = res.reindex(columns=columns_order, copy=True)
    
    return res

In [203]:
# test de la fonction "transform"
transformed_data = transform(data = extracted_data)
transformed_data

,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,winddir3pm,...,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,year,month,day
0,Ballarat,6.5,12.2,2.4,NaN,NaN,SW,44.0,SW,SSW,...,1020.0,7.0,4.0,8.4,11.3,Yes,No,2023,6,1
1,Ballarat,-0.7,11.4,0.0,NaN,NaN,N,28.0,E,N,...,1022.5,8.0,4.0,5.0,9.8,No,Yes,2023,6,2
2,Ballarat,5.0,14.7,3.8,NaN,NaN,ESE,41.0,NNW,,...,1026.1,8.0,8.0,9.0,14.1,Yes,No,2023,6,3
3,Ballarat,6.4,17.4,0.4,NaN,NaN,NNE,48.0,,NE,...,1027.5,NaN,NaN,10.4,16.6,No,No,2023,6,4
4,Ballarat,10.3,14.6,0.2,NaN,NaN,NNE,54.0,NE,NE,...,1021.8,1.0,8.0,12.4,11.8,No,Yes,2023,6,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396,Perth,2.8,16.4,1.0,2.8,9.3,NE,28.0,E,NE,...,1027.5,0.0,0.0,9.1,15.7,Yes,No,2023,7,15
2397,Perth,1.9,19.0,0.0,2.8,9.4,NNE,33.0,NE,N,...,1022.1,0.0,0.0,10.0,18.4,No,No,2023,7,16
2398,Perth,6.8,20.7,0.0,1.0,4.9,NNE,17.0,NNE,ESE,...,1020.9,7.0,3.0,11.8,19.5,No,No,2023,7,17
2399,Perth,7.6,19.4,0.0,0.8,1.5,NNW,41.0,N,NW,...,1012.1,7.0,8.0,13.6,19.0,No,Yes,2023,7,18
2400,Perth,10.9,NaN,21.8,2.8,NaN,NaN,NaN,SW,SW,...,1017.5,7.0,4.0,11.7,14.9,Yes,None,2023,7,19

In [204]:
transformed_data["location"].unique()

array(['Ballarat', 'Wollongong', 'Penrith', 'Cobar', 'Launceston',
       'SalmonGums', 'Cairns', 'Portland', 'Newcastle', 'Richmond',
       'Nuriootpa', 'Sydney', 'Witchcliffe', 'Williamtown', 'Albury',
       'Uluru', 'AliceSprings', 'Adelaide', 'Tuggeranong', 'Albany',
       'BadgerysCreek', 'PerthAirport', 'MountGambier', 'Woomera',
       'Moree', 'NorfolkIsland', 'MountGinini', 'Darwin', 'Walpole',
       'Sale', 'WaggaWagga', 'Mildura', 'Watsonia', 'Canberra',
       'NorahHead', 'MelbourneAirport', 'Melbourne', 'Townsville',
       'CoffsHarbour', 'SydneyAirport', 'Katherine', 'Hobart', 'Nhil',
       'Brisbane', 'PearceRAAF', 'Dartmoor', 'GoldCoast', 'Bendigo',
       'Perth'], dtype=object)

In [205]:
'Ballarat' in transformed_data["location"].unique()

True

In [207]:
transformed_data[transformed_data["location"] == "Ballarat"]

,location,mintemp,maxtemp,rainfall,evaporation,sunshine,windgustdir,windgustspeed,winddir9am,winddir3pm,...,pressure3pm,cloud9am,cloud3pm,temp9am,temp3pm,raintoday,raintomorrow,year,month,day
0,Ballarat,6.5,12.2,2.4,NaN,NaN,SW,44.0,SW,SSW,...,1020.0,7.0,4.0,8.4,11.3,Yes,No,2023,6,1
1,Ballarat,-0.7,11.4,0.0,NaN,NaN,N,28.0,E,N,...,1022.5,8.0,4.0,5.0,9.8,No,Yes,2023,6,2
2,Ballarat,5.0,14.7,3.8,NaN,NaN,ESE,41.0,NNW,,...,1026.1,8.0,8.0,9.0,14.1,Yes,No,2023,6,3
3,Ballarat,6.4,17.4,0.4,NaN,NaN,NNE,48.0,,NE,...,1027.5,NaN,NaN,10.4,16.6,No,No,2023,6,4
4,Ballarat,10.3,14.6,0.2,NaN,NaN,NNE,54.0,NE,NE,...,1021.8,1.0,8.0,12.4,11.8,No,Yes,2023,6,5
5,Ballarat,10.9,13.5,5.2,NaN,NaN,NNE,50.0,NNE,N,...,1019.6,8.0,8.0,11.2,12.5,Yes,No,2023,6,6
6,Ballarat,11.2,14.5,0.8,NaN,NaN,N,70.0,NNE,N,...,1012.5,8.0,8.0,13.0,14.0,No,Yes,2023,6,7
7,Ballarat,7.7,11.4,46.2,NaN,NaN,N,52.0,NW,NNW,...,1008.2,2.0,8.0,9.6,9.6,Yes,Yes,2023,6,8
8,Ballarat,4.9,11.4,3.8,NaN,NaN,NW,56.0,WNW,WNW,...,1015.2,NaN,8.0,7.6,9.7,Yes,No,2023,6,9
9,Ballarat,4.4,11.7,0.2,NaN,NaN,NNW,37.0,N,NW,...,1021.3,8.0,8.0,6.6,11.2,No,No,2023,6,10
10,Ballarat,6.5,11.7,0.0,NaN,NaN,N,30.0,NNE,N,...,1022.1,6.0,8.0,9.5,10.6,No,No,2023,6,11
11,Ballarat,5.6,11.4,0.4,NaN,NaN,N,50.0,NNE,N,...,1014.6,6.0,8.0,7.8,10.2,No,Yes,2023,6,12
12,Ballarat,6.7,11.2,1.0,NaN,NaN,N,54.0,N,NW,...,1006.0,8.0,8.0,7.4,9.6,Yes,Yes,2023,6,13
13,Ballarat,6.8,11.8,4.2,NaN,NaN,WNW,39.0,W,WNW,...,1014.5,7.0,8.0,7.5,10.8,Yes,Yes,2023,6,14
14,Ballarat,5.4,12.0,1.0,NaN,NaN,NNW,41.0,N,NNW,...,1014.1,8.0,8.0,9.0,10.6,Yes,No,2023,6,15
15,Ballarat,6.6,14.3,0.6,NaN,NaN,N,57.0,N,N,...,1015.2,NaN,1.0,7.5,13.6,No,No,2023,6,16
16,Ballarat,4.6,13.6,0.0,NaN,NaN,NW,65.0,N,N,...,1008.6,NaN,1.0,5.5,13.5,No,Yes,2023,6,17
17,Ballarat,2.5,10.8,9.0,NaN,NaN,NW,48.0,N,NW,...,1012.1,NaN,8.0,5.0,10.4,Yes,Yes,2023,6,18
18,Ballarat,3.8,7.9,7.6,NaN,NaN,W,46.0,W,WSW,...,1014.0,8.0,NaN,4.7,5.9,Yes,Yes,2023,6,19
19,Ballarat,-2.8,9.9,1.4,NaN,NaN,W,22.0,WNW,WNW,...,1023.4,NaN,7.0,2.3,8.1,Yes,No,2023,6,20
20,Ballarat,-0.8,7.3,0.0,NaN,NaN,N,37.0,NW,N,...,1020.6,NaN,8.0,3.2,6.3,No,No,2023,6,21
21,Ballarat,3.1,8.5,0.2,NaN,NaN,N,61.0,NNE,NNE,...,1008.1,8.0,8.0,5.3,7.1,No,Yes,2023,6,22
22,Ballarat,3.8,8.8,6.4,NaN,NaN,NNE,43.0,NNE,W,...,1004.4,8.0,8.0,5.5,7.5,Yes,No,2023,6,23
23,Ballarat,4.8,9.7,0.6,NaN,NaN,N,52.0,N,N,...,1004.3,7.0,8.0,6.0,9.3,No,Yes,2023,6,24
24,Ballarat,3.6,10.0,1.4,NaN,NaN,NW,61.0,N,NNW,...,1004.4,8.0,8.0,3.8,9.6,Yes,Yes,2023,6,25
25,Ballarat,3.8,11.6,1.2,NaN,NaN,W,46.0,W,W,...,1014.9,7.0,8.0,8.2,10.6,Yes,No,2023,6,26
26,Ballarat,2.7,9.1,0.6,NaN,NaN,N,37.0,N,N,...,1017.7,8.0,4.0,5.8,8.9,No,No,2023,6,27
27,Ballarat,4.1,9.4,0.0,NaN,NaN,WSW,39.0,NNW,SSW,...,1016.6,7.0,8.0,6.0,7.9,No,Yes,2023,6,28
28,Ballarat,2.4,8.9,1.4,NaN,NaN,W,43.0,W,W,...,1019.3,5.0,8.0,4.5,8.4,Yes,No,2023,6,29
29,Ballarat,4.3,12.1,0.8,NaN,NaN,W,46.0,W,W,...,1019.7,8.0,8.0,7.7,11.9,No,Yes,2023,6,30
30,Ballarat,5.1,11.5,2.2,NaN,NaN,S,33.0,SW,S,...,1026.5,8.0,8.0,7.4,8.1,Yes,No,2023,7,1
31,Ballarat,6.2,9.6,0.6,NaN,NaN,SSE,35.0,SSE,S,...,1033.3,8.0,8.0,7.0,9.2,No,No,2023,7,2
32,Ballarat,2.7,11.4,0.2,NaN,NaN,NNE,33.0,N,N,...,1024.9,1.0,4.0,4.8,10.4,No,No,2023,7,3
33,Ballarat,4.8,10.4,0.8,NaN,NaN,N,43.0,NNE,NNE,...,1012.2,8.0,8.0,8.3,9.3,No,Yes,2023,7,4
34,Ballarat,5.4,11.6,4.4,NaN,NaN,N,39.0,N,NNW,...,1011.4,8.0,1.0,7.3,10.7,Yes,No,2023,7,5
35,Ballarat,6.3,11.5,0.2,NaN,NaN,N,59.0,N,N,...,1005.6,8.0,8.0,7.1,9.9,No,Yes,2023,7,6
36,Ballarat,6.0,11.1,2.0,NaN,NaN,N,61.0,WNW,NNW,...,1009.9,8.0,7.0,7.5,10.3,Yes,Yes,2023,7,7
37,Ballarat,6.6,10.5,3.8,NaN,NaN,W,72.0,NW,WNW,...,1007.7,6.0,4.0,7.4,9.0,Yes,Yes,2023,7,8
38,Ballarat,6.0,12.5,4.4,NaN,NaN,WNW,50.0,W,W,...,1017.7,NaN,8.0,9.0,11.4,Yes,Yes,2023,7,9
39,Ballarat,7.7,11.7,1.4,NaN,NaN,NNW,50.0,N,NNW,...,1020.6,8.0,7.0,8.4,10.9,Yes,No,2023,7,10
40,Ballarat,7.7,14.6,0.8,NaN,NaN,W,33.0,NNE,W,...,1026.4,7.0,8.0,9.2,13.7,No,No,2023,7,11
41,Ballarat,7.4,13.7,0.0,NaN,NaN,NW,48.0,N,NW,...,1027.0,2.0,2.0,8.7,12.7,No,No,2023,7,12
42,Ballarat,3.5,11.5,0.0,NaN,NaN,N,59.0,N,N,...,1022.5,2.0,2.0,6.0,10.8,No,No,2023,7,13
43,Ballarat,5.0,10.8,0.0,NaN,NaN,N,54.0,N,N,...,1016.7,7.0,7.0,5.2,9.7,No,No,2023,7,14
44,Ballarat,4.2,8.3,0.0,NaN,NaN,N,33.0,N,SW,...,1020.7,8.0,8.0,6.8,8.1,No,No,2023,7,15
45,Ballarat,-2.4,11.6,0.2,NaN,NaN,WSW,28.0,SW,SW,...,1029.3,2.0,8.0,5.5,10.0,No,No,2023,7,16
46,Ballarat,-1.2,11.0,0.2,NaN,NaN,N,39.0,NNE,N,...,1026.4,NaN,NaN,4.6,10.8,No,No,2023,7,17
47,Ballarat,2.5,10.7,0.2,NaN,NaN,WSW,46.0,N,SW,...,1021.8,7.0,6.0,3.6,7.9,No,Yes,2023,7,18
48,Ballarat,-3.1,NaN,1.6,NaN,NaN,NaN,NaN,N,N,...,1023.0,NaN,7.0,0.9,10.0,Yes,None,2023,7,19

In [12]:
# chargement
def load(target_file, data_to_load):
    data_to_load.to_csv(target_file, index = False)

In [13]:
# executer les opération ETL sur le paquet des données récentes

# dossier des fichiers csv à manipuler
input_path = "../../datasets/raw/latest/*.csv"

# chemin de sauvegarde du fichier final
output_path = '../../datasets/processed/latest/processed-weather-aus-latest.csv'

# execution du pipeline ETL
extracted_data = extract(folder = input_path)
transformed_data = transform(data = extracted_data)
loaded_data = load(target_file = output_path, data_to_load = transformed_data)

In [14]:
# executer les opération ETL sur un paquets d'anciennes données

# dossier des fichiers csv à manipuler
input_path = "../../datasets/raw/may2022-may2023/*.csv"

# chemin de sauvegarde du fichier final
output_path = '../../datasets/processed/may2022-may2023/processed-weather-aus-may2022-may2023.csv'

# execution du pipeline ETL
extracted_data = extract(folder = input_path)
transformed_data = transform(data = extracted_data)
loaded_data = load(target_file = output_path, data_to_load = transformed_data)

In [15]:
# fusion et sauvegarde des données anciennes et récentes

df_1 = pd.read_csv('../../datasets/processed/dec2008-june2017/processed-weather-aus-dec2008-june2017.csv')
df_2 = pd.read_csv('../../datasets/processed/may2022-may2023/processed-weather-aus-may2022-may2023.csv')
df_3 = pd.read_csv('../../datasets/processed/latest/processed-weather-aus-latest.csv')

df_1_2_merged = pd.concat([df_1, df_2], ignore_index = True)

df_1_2_merged.to_csv('../../datasets/processed/dec2008-may2023/processed-weather-aus-dec2008-may2023.csv', index = False)

df_merged = pd.concat([df_1_2_merged, df_3], ignore_index = True)

save_path = '../../datasets/processed/up-to-date/processed-weather-aus-up-to-date.csv'

df_merged.to_csv(save_path, index = False)